### PR TITLE
Adding enrolled membership details

### PR DESCRIPTION
**Pull request by mathew-litmus7**
### Summary
Displays the enrolled memberships of the customer

### CODE REVIEW

**Review by jrmihalick — CHANGES_REQUESTED** [review]
See my comment about adding a screenshot

**Comment by mathew-litmus7** [comment]
Hi Jason,

 

Updated screenshot in PR.

 

Thanks,

Mathew

**Comment by mathew-litmus7** [comment]
> @mathew-litmus7 Could you attach a screenshot of how this looks?
Capture

**Comment by jrmihalick** [comment]
@mathew-litmus7 Did you check how it looks on mobile, like with a resolution of 360x640?

**Comment by mlitmus7** [comment]
Capture
mobile view

**Comment by jrmihalick** [comment]
We should fix the spacing between the button icon and the button text on the enrollment buttons in the mobile view, but that is a problem on the secondary button component.

**Review by jrmihalick — APPROVED** [review]

**Pull request merged**
