### PR TITLE
Loyalty Button layout changes

### PR DESCRIPTION
**Pull request by r-cochran**
### Summary
Changed the layout/styling to the loyalty button when a customer is linked.

### Screenshots
Default
image
image

dark-blue (the icon being white is an artifact of the image for the inverted logo colors being white, this would be tailored per customer)
image
image

pets
image
image

training
image
image

patriotic bird
image
image

patriotic nest
image
image

burl red
image
image

bang orange
image
image

### CODE REVIEW

**Review by jrmihalick — APPROVED** [review]

**Comment by r-cochran** [comment]
> Looks good, Petco wanted the shortened name of the groups to be displayed on the Loyalty button. Will that be possible with this implementation?

good callout I had forgotten that part. I believe it was discussed as using the ID instead of the name of the group. We currently don't have a short name field for the customer groups table, but might be something to expand into.

**Comment by mmichalek** [comment]
I don't think we can use group id for this. I think we will need a "shortDescription" field on the group model.  If it's populated, then we can use it there on the sale screen.  If it's not populated, then use the current displayValue.

**Comment by jrmihalick** [comment]
Now is the time to add it, I think.  QA will probably flag it anyway.

**Comment by r-cochran** [comment]
made the changes, but they were all commerce side. @mmichalek was there anything else to tweak on the openpos side?

**Review by mmichalek — APPROVED** [review]

**Comment by mmichalek** [comment]
Looks good Robert.

**Pull request merged**
