### PR TITLE
Bugfix/item void hot key always removes first item from basket

### PR DESCRIPTION
**Pull request by blubaugha**
# Fixes
This fixes a bug where the `Item-Void` keybinding would always remove the first item from a sale. It was caused by some extra subscriptions that weren't cleaned up after each time the screen data updated.

**Hot key for item void always removing first item from basket vs selected item from basket. #1509**
https://github.com/JumpMind/commerce/issues/1509

# Examples
**Selecting Items with Mouse**
remove-item-shortcut-key-always-removing-first-item-fix--mouse

**Selecting Items with Keyboard**
remove-item-shortcut-key-always-removing-first-item-fix

### CODE REVIEW

**Comment by jrmihalick** [comment]
Anyone have any theories on why we are getting a ton of merge commits in openpos-framework?  I am seeing the same thing when I do PRs?

**Comment by stevencarley** [comment]
> Anyone have any theories on why we are getting a ton of merge commits in openpos-framework? I am seeing the same thing when I do PRs.

You could try on your master branch `git pull` then `git reset --hard`, this will delete any local changes and reset the index of the branch. The when you create a new branch from master it _should_ get rid of the extra merges.

**Comment by jrmihalick** [comment]
> > Anyone have any theories on why we are getting a ton of merge commits in openpos-framework? I am seeing the same thing when I do PRs.
> 
> You could try on your master branch `git pull` then `git reset --hard`, this will delete any local changes and reset the index of the branch. The when you create a new branch from master it _should_ get rid of the extra merges.

I did that a few days ago and it worked for a couple of days, then started again.

**Comment by blubaugha** [comment]
> Is the `takeUntil(this.stop$)` which is preventing subscriptions from accumulating?

Yeah, when the `takeUntil` receives an update from the `stop$` observable (when either `disposed$ or `beforeScreenDataUpdated$` is updated) the subscription is removed.

**Pull request merged**
