### PR TITLE
Auto-focus on first options element

### PR DESCRIPTION
**Pull request by JJStarrett**
### Issues Fixed
 - [4103](https://petcoalm.atlassian.net/browse/PDPOS-4103)

### Summary
The first element of each options list can now optionally be auto-focused.

### Screenshots
23cd2b4ecc5c6fca89a70bee24b9eec4

### CODE REVIEW

**Review by stojankz — APPROVED** [review]

**Review by chenson42 — APPROVED** [review]

**Comment by chenson42** [comment]
I wonder if this should be configurable from the server ui message?

**Comment by JJStarrett** [comment]
> I wonder if this should be configurable from the server ui message?

I'm not completely sure what the server ui message is, but I'd be happy to implement it.

**Comment by chenson42** [comment]
I was thinking maybe on OptionsListPart.java you add a setting as to whether the first item gets active focus or not.   I can imagine there are times when we'll want to the user to explicitly choose something.

**Review by dankaste — APPROVED** [review]

**Comment by JJStarrett** [comment]
> I was thinking maybe on OptionsListPart.java you add a setting as to whether the first item gets active focus or not. I can imagine there are times when we'll want to the user to explicitly choose something.

Added.

**Review by chenson42 — APPROVED** [review]

**Pull request merged**
