### PR TITLE
Sale Screen layout Fix

### PR DESCRIPTION
**Pull request by r-cochran**
### Summary
fixed a misplaced div that caused the sale screen to not display all of the cart details and checkout functionality

### Screenshots
before
image

after
image

### CODE REVIEW

**Comment by stojankz** [comment]
hm.. did you test this change running commerce demo at all? I don't see this happen running demo fashion so I'm a little worried to update the openpos component without thorough testing
Screen Shot 2021-11-29 at 1 33 20 PM

**Review by chenson42 — APPROVED** [review]

**Comment by r-cochran** [comment]
> 
I had not, but good call out. It looks to display correctly with the change in this PR.

image

If I swap back to master this is what I get

image

I think this might have been a mistake introduced with [this change](https://github.com/JumpMind/openpos-framework/commit/2f768f2f85a43ea4025971f853f5bce4a2e6e48d)

**Comment by stojankz** [comment]
> > 
> 
> I had not, but good call out. It looks to display correctly with the change in this PR.
> 
> image
> 
> If I swap back to master this is what I get
> 
> image
> 
> I think this might have been a mistake introduced with [this change](https://github.com/JumpMind/openpos-framework/commit/2f768f2f85a43ea4025971f853f5bce4a2e6e48d)

ah okay, looks like it broke today and I don't have that change pulled in which is why I did not see it.

**Review by stojankz — APPROVED** [review]

**Comment by chenson42** [comment]
Yeah.  That is why I so quickly approved it.

**Pull request merged**
