### PR TITLE
Merge/1 9 to master

### PR DESCRIPTION
**Pull request by eddielegg-le**
### Summary
Merge releases/1.9 into master

### CODE REVIEW

**Comment by jrmihalick** [comment]
I see several changes in here that were not specific to 1.9, but were in 1.8 as well.  Just wondering to myself why they didn't get merged previously with the 1.8->master merge?

**Review by jrmihalick — APPROVED** [review]

**Comment by chenson42** [comment]
> I see several changes in here that were not specific to 1.9, but were in 1.8 as well. Just wondering to myself why they didn't get merged previously with the 1.8->master merge?

We never did merge 1.8 > master.  We were relying on cherry picking.

**Comment by chenson42** [comment]
@eddielegg-le  Make sure we don't merge this until commerce is ready too!

**Review by chenson42 — APPROVED** [review]

**Comment by jrmihalick** [comment]
> We never did merge 1.8 > master. We were relying on cherry picking.

Oh, so you didn't merge 1.8 -> master for openpos, but you did for commerce?

**Comment by chenson42** [comment]
> > We never did merge 1.8 > master. We were relying on cherry picking.
> 
> Oh, so you didn't merge 1.8 -> master for openpos, but you did for commerce?

This is the first merge of either.  Commerce has yet to be done.

**Review by blubaugha — APPROVED** [review]

**Pull request closed without merging**
