### PR TITLE
removed the default dialog close on ESC

### PR DESCRIPTION
**Pull request by chandankumarcentric**
fixed https://github.com/JumpMind/commerce/issues/8434
PDPOS - https://petcoalm.atlassian.net/browse/PDPOS-10472

PDPOS - https://petcoalm.atlassian.net/browse/PDPOS-9906

fix - Now pressing ESC key will only close the dialog if it is binded on some button/action on backend.

### CODE REVIEW

**Review by jrmihalick — APPROVED** [review]

**Comment by jrmihalick** [comment]
Undoing changes made on #1948 and #1985 .  @brandon-lewis let me know if any concerns other than the obvious which is that we now won't be allowing dialogs to be closable by default.

**Comment by chandankumarcentric** [comment]
https://user-images.githubusercontent.com/104163681/208917566-74f53529-5e60-4af7-a8b5-579906fad62a.mp4

**Comment by chandankumarcentric** [comment]
https://user-images.githubusercontent.com/104163681/208918761-535919eb-05da-4fda-8360-7e8f336550ab.mp4

**Comment by chandankumarcentric** [comment]
POP_TART will still be closed automatically when clicked outside the dialog or by pressing ESC without key binding because we are setting disableClose = false in below code:
  openPopTart() {
    const dialogRef = this.dialog.open(PopTartComponent, {
      width: '70%',
      data: {
        optionItems: this.values,
        instructions: (this.formField as IPopTartField).instructions,
        searchable: (this.formField as IPopTartField).searchable,
        limit: (this.formField as IPopTartField).limit,
        disableClose: false,
        autoFocus: false
      }
    });
    
    A per angular material the dialog gets closed by clicking outside the dialog or by pressing ESC button if the disableClose is set to false.
https://material.angular.io/components/dialog/api

**Pull request merged**
