### PR TITLE
Improve the management of sql & csv scripts

### PR DESCRIPTION
**Pull request by chenson42**
### Summary
We now support running sql scripts again if they have changed.  The name of the file and the md5 checksum is stored in a {module_prefix}_script_version table.  If a file has changed (its checksum changed) then it is run again.   This means that if files change they need to be rerunnable.   For CSV files, if they have changed then the table is truncated and reloaded.

### Parameter Changes
- The `openpos.general.sqlScriptProfile` parameter has been deprecated.

### Database Changes
- A new table was added that tracks files that have been run. `{module_prefix}_script_version`

### CODE REVIEW

**Comment by mmichalek** [comment]
I like it, this will help a lot.  I am nervous about the "truncate" part of the CSV.  Seems like that could happen in production at the wrong time.

**Comment by chenson42** [comment]
> I like it, this will help a lot. I am nervous about the "truncate" part of the CSV. Seems like that could happen in production at the wrong time.

Maybe I should make that configurable?

**Comment by mmichalek** [comment]
Yeah that might help.  There was also this idea from Petco where when we go to prod central, we might want commerce to generate DLL scripts instead of directly applying the DLL changes to the central DB.  So maybe this could work in conjunction with that config where the system creates a package of scripts to run instead of directly applying them.

**Comment by mmichalek** [comment]
Another thought for the CSV: could we add support for SQL commands in there? So the CSV's could be written to run safely repeatable like the other .sql scripts. Like:
`SQL_CMD,delete from blah where foo='bar'`

**Comment by jrmihalick** [comment]
> > I like it, this will help a lot. I am nervous about the "truncate" part of the CSV. Seems like that could happen in production at the wrong time.
> 
> Maybe I should make that configurable?

You'd probably want to also have the ability to control what specific entities are ok to truncate and which aren't, with the default being that none are truncated.  I think it would also make sense to have all of this configuration in it's own yaml file, for easier review/update.

**Review by dankaste — APPROVED** [review]

**Review by stevencarley — APPROVED** [review]

**Pull request merged**
